version: '3'

services:
  frappe:
    image: registry.cn-beijing.aliyuncs.com/lvxj11/erpnext:V12
    restart: on-failure
    environment:
      - MARIADB_ROOT_PASSWORD=Pass0129
      - ADMIN_PASSWORD=admin
    ports:
      - "31010:80"
      - "31011:443"
      - "31012:8000"
    depends_on:
      - redis
      - mariadb
    links:
      - redis
      - mariadb
    volumes:
      - frappe-bench-vol:/home/frappe/frappe-bench:rw
      - frappe-nginx-vol:/etc/nginx

  redis:
    image: redis:5
    restart: on-failure
    volumes:
      - redis-vol:/data

  mariadb:
    image: mariadb:10.3
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=Pass0129
    ports:
      - "31013:3306"
    volumes:
      - ./frappe-mariadb.cnf:/etc/mysql/conf.d/frappe.cnf
      - mariadb-vol:/var/lib/mysql

volumes:
  mariadb-vol:
  redis-vol:
  frappe-bench-vol:
  frappe-nginx-vol:
