# Frappe Bench Dockerfile
FROM python:3.8
LABEL author=lvxj11

# 前期准备，设置环境语言安装必要软件，新建用户并添加sudo权限。
RUN apt update \
  && apt upgrade -y \
  && apt install -y \
    git \
    mariadb-client \
    postgresql-client \
    gettext-base \
    wget \
    # for PDF
    libjpeg62-turbo \
    libx11-6 \
    libxcb1 \
    libxext6 \
    libxrender1 \
    libssl-dev \
    fonts-cantarell \
    xfonts-75dpi \
    xfonts-base \
    # to work inside the container
    locales \
    build-essential \
    cron \
    curl \
    vim \
    sudo \
    iputils-ping \
    watch \
    tree \
    nano \
    software-properties-common \
    bash-completion \
    # For psycopg2
    libpq-dev \
  && wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.buster_amd64.deb \
  && dpkg -i wkhtmltox_0.12.5-1.buster_amd64.deb && rm wkhtmltox_0.12.5-1.buster_amd64.deb \
  && apt-get autoremove -y \
  && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
  && dpkg-reconfigure --frontend=noninteractive locales \
  && export LANG=C.UTF-8 \
  && export LC_ALL=C.UTF-8 \
  && groupadd -g 1000 frappe \
  && useradd --no-log-init -r -m -u 1000 -g 1000 -G  sudo frappe \
  && echo "frappe ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# 设置运行用户与目录
USER frappe
WORKDIR /home/frappe

# 下载脚本，修改脚本，运行安装脚本。
RUN cd /home/frappe \
  && export LANG=C.UTF-8 \
  && export LC_ALL=C.UTF-8 \
  && wget https://raw.githubusercontent.com/frappe/bench/develop/install.py \
  && sudo sed -i -e 's/pass_set = True/pass_set = False/' /home/frappe/install.py \
  && sudo python3 install.py --production --mysql-root-password Pass0129 --admin-password admin

# 开放端口
EXPOSE 80 443 8000

# 卷目录
VOLUME /home/frappe/frappe-bench/sites
